v = int(input("Enter a number: "))
n = v
print ("Largest: " + str ( n))
v = int(input("Enter a number: "))
n = max (v, n)
print ("Largest: " + str ( n))
v = int(input("Enter a number: "))
n = max (v, n)
print ("Largest: " + str ( n))
v = int(input("Enter a number: "))
n = max (v, n)
print ("Largest: " + str ( n))
v = int(input("Enter a number: "))
n = max (v, n)
print ("Largest: " + str ( n))
v = int(input("Enter a number: "))
n = max (v, n)
print ("Largest: " + str ( n))
