#!/usr/bin/env python3
# Base 10 to Base 16 CWColeman
print ("DECIMAL", 0,"= HEXADECIMAL", hex(0))
print ("DECIMAL", 1,"= HEXADECIMAL", hex(1))
print ("DECIMAL", 2,"= HEXADECIMAL", hex(2))
print ("DECIMAL", 3,"= HEXADECIMAL", hex(3))
print ("DECIMAL", 4,"= HEXADECIMAL", hex(4))
print ("DECIMAL", 5,"= HEXADECIMAL", hex(5))
print ("DECIMAL", 6,"= HEXADECIMAL", hex(6))
print ("DECIMAL", 7,"= HEXADECIMAL", hex(7))
print ("DECIMAL", 8,"= HEXADECIMAL", hex(8))
print ("DECIMAL", 9,"= HEXADECIMAL", hex(9))
print ("DECIMAL", 10,"= HEXADECIMAL", hex(10))
print ("DECIMAL", 11,"= HEXADECIMAL", hex(11))
print ("DECIMAL", 12,"= HEXADECIMAL", hex(12))
print ("DECIMAL", 13,"= HEXADECIMAL", hex(13))
print ("DECIMAL", 14,"= HEXADECIMAL", hex(14))
print ("DECIMAL", 15,"= HEXADECIMAL", hex(15))
print ("DECIMAL", 16,"= HEXADECIMAL", hex(16))
