# code 1.3 plus cwc

print("Hello world")
print ("Welcome to Computer Science!")
print("Hello")
print("There")
print(" * * * * * * * * * ")
print(" ^   ^  ")
print("( o  o )")
print("    v   ")
print(" * * * * * * * * * ")
print(" _   _")
print("(,)_(,)")
print(" | ''|")
print("=|  @|=")
print("  --- ")
print(" * * * * * * * * * ")
print(" __")
print("('')")
print("( (")
print(" ) )")
print("( (")
print(" ) )")
print("( (")
print(" ) )")
print("( (")
print(" ) )")
print("  V")
print(" * * * * * * * * * ")
'''
Escape Character	Meaning
\n	Create a new line
\t	Tab for extra spacing
\"	Quotation mark
\\	Backslash
'''
print ("A lightning flash:\nbetween the forest trees\nI have seen water.\n\t- Shiki")
print(" * * * * * * * * * ")
print("**********\n*        *\n* PYTHON *\n*        *\n**********")
print(" * * * * * * * * * ")
print ("A lightning flash:\nbetween the forest trees\nI have seen water.\n- Shiki")
print(" * * * * * * * * * ")
print("              )")
print("             ( ")
print("         ^    )")
print("        / \ ---")
print("       /   \| |")
print("      /  _  \ |")
print("     /  (_)  \|")
print("    /         \\")
print("   /|   _   _  \\")
print("    |  | | | |  \\")
print("    |  |_| |_|  |\\")
print("    |   __   __ |")
print("    |  |  | |  ||      #")
print("    |  | @| |__||     ###")
print("    |  |  |     |    #####")
print(" \/\/\/\/\/\/\/\/\/\/\/\/\/")
print(" * * * * * * * * * ")
print("A lightning flash:\nbetween the forest trees\nI have seen water.\n- Shiki")
print(" * * * * * * * * * ")
print("\"Computer Science is no more about computers\n than astronomy is about telescopes\"\n - Edsger W. Dijkstra")
print(" * * * * * * * * * ")
print(" * * * * * * * * * ")
print(" * * * * * * * * * ")
print(" * * * * * * * * * ")

