print('              )')
print('             ( ')
print('         ^    )')
print('        / \ ---')
print('       /   \| |')
print('      /  _  \ |')
print('     /  (_)  \|')
print('    /         \\')
print('   /|   _   _  \\')
print('    |  | | | |  \\')
print('    |  |_| |_|  |\\')
print('    |   __   __ |')
print('    |  |  | |  ||      #')
print('    |  | @| |__||     ###')
print('    |  |  |     |    #####')
print(' \/\/\/\/\/\/\/\/\/\/\/\/\/')
