name = input( "Enter a name: ")
adj1 = input ("Enter an adjective: ")
adj2 = input("Enter an adjective: ")
adv = input("Enter an adverb: ")
food1 = input("Enter a food: ")
food2 = input("Enter another food: ")
noun = input("Enter a noun: ")
place = input ("Enter a place: ")
verb = input ("Enter a verb: ")

print (name+" was planning a dream vacation to "+place)
print (name+" was especially looking forward to trying the local")
print ("cuisine, including "+adj1+" "+food1+" and "+food2+".")
print ("\n"+name+ "will have to practice the language "+ adv+" to")
print ("make it easier to "+verb+" with people.")
print ("\n"+name+ " has a long list of sights to see, including the")
print (noun + " museum and the "+ adj2+" park.")
